apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-app
spec:
  selector:
    matchLabels:
      app: payment-service-app
  template:
    metadata:
      labels:
        app: payment-service-app
    spec:
      containers:
      - name: payment-service-app
        image: asadullah1005/payment-service
        ports:
        - containerPort: 8081
        env:
        - name: CONFIG_SERVER
          valueFrom:
            configMapKeyRef:
              name: config-cm
              key: config_server_address
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-cm
              key: hostname

---

apiVersion: v1
kind: Service
metadata:
  name: payment-service-svc
spec:
  selector:
    app: payment-service-app
  ports:
  - port: 80
    targetPort: 8081

